autoenc_ckpt: 0--best-epoch=99.ckpt
autoenc_hash: 2665f7b6c849de22da095edebbc16d64
batch_size: 8
cos_weight: 0.33
dataset: goes16_rj_FI_darts_rain_events
image_weight: 0.5
latent_model_name: Maxvit
lead_time_cond: 1
learning_rate: 0.0001
maxvit_depth: 4
maxvit_dim: 64
maxvit_downsample: 0
model_name: tupann
n_epochs: 20
optim: adam
predict_all_times: 1
res_modification: 0
use_detach: 1
use_pred_image: 1
use_time_decay: 0
use_vectors_and_intensities: 0
vector_weight: 0.1
